package:
  name: thermotools
  version: "0.1.3"

source:
  fn: thermotools-0.1.3.tar.gz
  url: https://pypi.python.org/packages/source/t/thermotools/thermotools-0.1.3.tar.gz

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20
    - numpy >=1.7

  run:
    - python
    - numpy >=1.7

test:
  requires:
    - nose
    - coverage
  imports:
    - thermotools

about:
  home: https://github.com/markovmodel/thermotools
  license: GNU Lesser Public License v3+
  summary: "Lowlevel implementation of free energy estimators"
